services:
  solana-cli:
    build:
      context: ./solana-cli

  plugin:
    build:
      context: ./geyser-plugin
      args:
        # https://github.com/helius-labs/geyser-lattice-test.git
        ZIP: https://github.com/helius-labs/geyser-lattice-test/archive/9c74f3fee547edcebd70d7daf6770822ed890a02.zip
        SRCDIR: /geyser-lattice-test-9c74f3fee547edcebd70d7daf6770822ed890a02
        LIB: libgeyser_lattice_test.so

  test-validator:
    build:
      context: ./solana-test-validator
      additional_contexts:
        solana-cli: service:solana-cli
        plugin: service:plugin
    depends_on:
      - plugin
    environment:
      - RPC_PORT=8899

  traffic-script:
    build:
      context: ./traffic-script
      additional_contexts:
        solana-cli: service:solana-cli
    depends_on:
      test-validator:
        condition: service_healthy
    environment:
      - RPC_PORT=8899
